# 외부라이브러리

## 넘파이 Numpy

In [1]:
import numpy

In [2]:
!pip install Pandas


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import pandas

In [4]:
!pip install Matplotlib

     ---------------------------------------- 0.0/113.8 kB ? eta -:--:--
     ---------- ---------------------------- 30.7/113.8 kB 1.4 MB/s eta 0:00:01
     -------------------------------------- 113.8/113.8 kB 2.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   --- ------------------------------------ 0.7/8.1 MB 14.5 MB/s eta 0:00:01
   ------------ --------------------------- 2.5/8.1 MB 31.8 MB/s eta 0:00:01
   ----------------- ---------------------- 3.6/8.1 MB 28.8 MB/s eta 0:00:01
   -------------------------------- ------- 6.7/8.1 MB 38.9 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 37.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/225.2 kB ? eta -:--:--
   ---------------------------------------- 225.2/225.2 kB ? eta 0:00:00
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------  2.3/2.3 MB 73.0 MB/s eta 0:00:01
   --------------------


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
#넘파이numpy 
#대수 행렬 통계 등 수학 및 과학 연산을 위한 라이브러리
#ndarray 라는 다차원 배열을 데이터로 나타내고 처리하는 데에 특화
#실행속도가 빠르고 짧고 간결한 코드 구현이 가능하다~~~

In [8]:
# np.arange (시작인덱스 : 끝인덱스 :간격)
arr1 = numpy.arange(0,10,2)
arr1

array([0, 2, 4, 6, 8])

In [11]:
# 넘파이는 한 가지 데이터 타입으로 통일
# 데이터 타입 우선 순위는 문자 실수 정수 (표현 범위가 더 큰 형태로됨)
# 데이터 타입 지정 가능함 이건 나중에................

list_data = [1,'2',3]
arr2 = numpy.array(list_data)
print(arr2)

['1' '2' '3']


In [13]:
#2차원 데이터를 행/열로 변경해주는 능력이 있음
# 3차원도 가능~~
# 3차원 데이터는?

arr3 = numpy.array([[[1,2,3,4],[5,6,7,8]],[9,10,11,12]])
print(arr3)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [15]:
#배열의 차원과 크기? ndim shape
#배열의 차원 변경 reshape  뒤에 마이너스를 써주면 알아서 차원을 만들어줌
#연산 : shape이 같다면 덧셈 뺄셈 곱셈 나눗젬을 할 수 있당 (오...행렬 대수같은 개념인가)

a =numpy.array([1,2,3])
b=numpy.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [16]:
import numpy as np

In [17]:
np.__version__

'2.3.3'

In [19]:
L = range(1000)
%timeit L2 = [i**2 for i in L]  #이건 리스트 만드는 거?

54.5 μs ± 5.97 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [18]:
arr = np.array(1000)
%timeit arr2 = arr**2

510 ns ± 51.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [20]:
alist = [1,2,3,4,5,6]

In [22]:
print(alist)
print(type(alist))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [28]:
np.array([1,2,np.nan,4])

array([ 1.,  2., nan,  4.])

In [31]:
arr1 = np.array([1,2,3,4])

print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
1
(4,)


In [32]:
arr2 = np.array([[1,2,3,4]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]]
2
(1, 4)


In [34]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [ ]:
arr3 = arr2.reshape(-1,3) ##마이너스는 배열을 3배수로 니가 *알아서* 정리하라는 거임 ㅎㅎ reshape - 는 하나만 넣을 수 있음.

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [ ]:
arr4 = arr2.reshape(-1,7)  ## >> 행열 배열의 사이즈가 12/7 나누어 떨어지지 않아 새로운 배열을 만들수가 없음. 그래서 에러남.

print(arr4)
print(arr4.ndim)
print(arr4.shape)

ValueError: cannot reshape array of size 12 into shape (7)

In [38]:
arr3 = arr2.reshape(2,-1,3)

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [39]:
alist =np.array([1,2,3,4,5])
blist =np.array([6,7,8,9,10])

In [ ]:
print(alist+blist) #같은 인덱스끼리 연산함.
print(alist-blist)
print(alist*blist)
print(alist/blist)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [41]:
arr1 = np.array([1,2,3,4])

print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
1
(4,)


In [43]:
arr5=arr1.reshape(4,1)
arr5

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(2*a+b)
print((a==2))
print(b>10)
print((a==2) & (b>10))  #and 는 에러남

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [ ]:
alist = [[0,1,2],[3,4,5]]  ##주의!! 파이선에서 첫번째는 항상 0 으로 인식
#0뽑기 1뽑기 5뽑기  리스트 이름 + 몇 번째 인지 입력 

print(alist[0]) #alist 에서 처음은 012니까 012산출
print(alist[0][0]) #alist에서 처음 = 012 리스트에서 0 첫번째
print(alist[0][1]) #alist에서 처음 = 012 리스트에서 1 두번째
print(alist[1][2]) #alist에서 처음 = 345 리스트에서 5 세번째

[0, 1, 2]
0
1
5


In [98]:
alist = [[0,1,2], [3,4,5]]
[alist[0][0],alist[0][1]]





[0, 1]

In [93]:
#슬라이싱 :2 ~~까지 꺼내줘
#0 1 슬라이싱 --> [0,1]
alist[0][:2]

[0, 1]

In [95]:
#슬라이싱 :2 ~~까지 꺼내줘 / 1: 1부터 꺼내줘
#4,5 [4,5]
alist[1][1:]

[4, 5]

In [97]:
#슬라이싱 :2 ~~까지 꺼내줘 / 1: 1부터 꺼내줘
#1.4 를 꺼내줘
aalist=[alist[0][1],alist[1][1]]
aalist

[1, 4]

In [100]:
arr_test = numpy.array([[0,1,2],[3,4,5]])
arr_test


array([[0, 1, 2],
       [3, 4, 5]])

In [127]:
print(arr_test[0,0])
print(arr_test[0,1])


0
1


In [112]:
arr_test[0,:2]

array([0, 1])

In [113]:
arr_test[1,1:]

array([4, 5])

In [ ]:
arr_test[-1,1:]   #마이너스 음수인덱싱은 맨마지막 거 가지고 오라는 뜻 1: 두번째=1 부터

array([4, 5])

In [ ]:
arr_test[:] # 모든행 선택

array([[0, 1, 2],
       [3, 4, 5]])

In [126]:
arr_test[:,1] # 모든행 + 그중에 1 라인 (두번째)

array([1, 4])

In [ ]:
print(arr_test[[0,1],[1,1]])

[1 4]


In [132]:
arr_test[0,1]

np.int64(1)

In [135]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a[0,:3]

array([0, 1, 2])

In [136]:
a[:,1]

array([1, 5])

In [137]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

In [138]:
clist = np.array([[0,1,2,4],[5,6,7,8],[9,10,11,12]])
clist
#슬라이싱 테스트 해보기


array([[ 0,  1,  2,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [140]:
clist[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [141]:
clist[-1:,1:]

array([[10, 11, 12]])

In [161]:
clist[:,2]
clist_1 = clist[:,2]

In [164]:
clist[:,-2:-1] #슬라이싱으로 행/열 나눠서 뽑으면 위치도 같게 뽑을 수 있음. 
## 요건 다시 생각해보기

array([[ 2],
       [ 7],
       [11]])

In [148]:
print(clist_1)
print(clist_1.ndim)
print(clist_1.shape)

[ 2  7 11]
1
(3,)


In [149]:
clist_1.reshape(3,1)

array([[ 2],
       [ 7],
       [11]])

### 팬시 인덱싱
불리언 방식?

In [ ]:
#fancy indexing --> 조건하에 원하는 데이터를 써내는 방법

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [151]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = [0,2,5]
a[idx]

array([0, 2, 5])

In [153]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [155]:
b[[0,2]] #0 행 2열 추출 . 정수인덱싱 불리언 인덱싱이 가능한 구조. >> 이게 뭔말이지 ㅋㅋ

array([[1, 2, 3],
       [7, 8, 9]])

In [156]:
arr = np.array([1,2,3,4,5,6,7,8])

In [157]:
arr % 2 ==0

array([False,  True, False,  True, False,  True, False,  True])

In [ ]:
arr[arr%2==0] # tRUE값만 산출함

array([2, 4, 6, 8])

In [160]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a%2==1]

array([1, 3, 5, 7, 9])

In [ ]:
a = np.array([[11,22,33,44,55,66,77,88,99])
idx = np.array([0,0,0,])
a

In [166]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [181]:
a[[2,0,1],:] ##원래 2번행 / 0번행 / 1번행 놓고 전부가져와

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [ ]:
np.array([a[2,:],a[0,:],a[1,:]]) ##위에걸 하나하나쓰면 이런 느낌인데, 공통인거 묶으면 됨.

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [167]:
a[:,[0,3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [170]:
a[2,:]

array([ 9, 10, 11, 12])

In [185]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
#3의 배수를 찾아주세요

x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [186]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [189]:
x[(x%3==0) & (x%4==1)]

array([9])

## Pandas
series / dataframe

데이터 프레임 맨 앞 열은 인텍스라고 부르고, 인덱스 명이 있음.
그 외에 옆에 붙은 건 행 열 같음.
대신 열은 앞에 인덱스가 있으니까 1부터 시작하는 거고,
행은 0부터 시작하고

데이터프레임의 최소단위? 같은 개념은 시리즈 이고..
시리즈는 인덱스 + 1열구조

In [ ]:
#딕셔너리로 표현 ({key : value, key : value}
#리스트로 표현도 가능하긴 함. 2차원 배열구조가 기본 ([[]])
#인덱스 열럼이름이 있으니까 컬럼명 확인..
# df.columns  +뒤에 컬럼 명도 가능
#데이터 양이 일반적으로 많으니까 ㅎㅎㅎ 그냥 오토 컬럼으로 지정하게 해는게 편함

#csv 파일을 읽어서 dataframe 객체를 변환해서 ㅇ ㅕㄴ결 가능~~
#컬럼별 통계량도 구핼 수 있음 데이터프레임이름.describe
# count / mean/std(표준편차)/min / 25% 50% 등등등

In [192]:
import pandas as pd

In [202]:
hero=pd.read_csv('heroes.csv')
hero

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [196]:
pd.options.display.float_format = '{:.0f}'.format
##데이터(숫자)가 너무 커서 보여지는 방식을 조정한거

In [ ]:
df = pd.DataFrame(hero)  # > df 볼거면  pd.dataframe으로 정의한번 해주고 가야함.

In [204]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [205]:
hero.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes
